# Generated by Django 2.2.12 on 2020-11-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_fac', '0002_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PersonName',
            field=models.CharField(max_length=300),
        ),
    ]
